apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: lance-etl-search
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: lance-etl-search
      app.kubernetes.io/track: stable
