apiVersion: v1
kind: Service
metadata:
  name: lance-etl-search
  labels:
    app.kubernetes.io/name: lance-etl-search
spec:
  selector:
    app.kubernetes.io/name: lance-etl-search
    app.kubernetes.io/track: stable
  ports:
    - name: grpc
      port: 8080
      targetPort: grpc
      protocol: TCP
