apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: lance-etl-reconciler
    app.kubernetes.io/component: executor
spec:
  serviceAccountName: lance-etl-executor
  securityContext:
    runAsNonRoot: true
    runAsGroup: 185
    runAsUser: 185
    fsGroup: 185
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: spark-kubernetes-executor
      image: ghcr.io/gstamatakis95/lance-etl-reconciler@sha256:0000000000000000000000000000000000000000000000000000000000000000
      env:
        - name: DD_SERVICE
          value: lance-etl-reconciler
        - name: DD_ENV
          valueFrom:
            configMapKeyRef:
              name: lance-etl-reconciler
              key: environment
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: temporary
          mountPath: /tmp
  volumes:
    - name: temporary
      emptyDir:
        sizeLimit: 20Gi
